### ISSUE TITLE
Any chance of retiring Lena from Sampledoc background?

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/sampledoc#14]
Copy of : https://github.com/matplotlib/matplotlib/issues/5220

I noticed just now that sampledoc:

http://matplotlib.org/sampledoc/index.html

uses Lena for the top banner lettering background. It would be good to change that for the usual reasons (questionable taste, copyright). Is that acceptable?

**Comment by efiring** [comment]
I don't see any problem with that; but at the same time, I'm amazed you even spotted it, given how obscure it is by being just that background, and how inactive sampledoc itself is.  Larger question: how much of sampledoc is out of date now?  How useful is it?

**Comment by matthew-brett** [comment]
I seem to hit that page fairly often because I'm a big user of the plot_directive.  

I can't seem to raise google.com at the moment, but a DuckDuckGo search of "matplotlib sphinx" gives http://matplotlib.org/sampledoc/extensions.html as the top hit.

**Comment by tacaswell** [comment]
Done in #15

**Comment by matthew-brett** [comment]
I notice Lena is stil there, in current http://matplotlib.org/sampledoc - does anything else need doing to complete this task?

**Comment by jenshnielsen** [comment]
Looks like it's coming from https://github.com/matplotlib/matplotlib.github.com/tree/master/sampledoc which contains a manual build (from 2013 by the looks of it). I guess that just needs to be rebuild and pushed

**Comment by tacaswell** [comment]
I will do that when I get to a non-mobile internet connection.

**Comment by matthew-brett** [comment]
I did some cleanup here : https://github.com/matplotlib/sampledoc/pull/17 - maybe merge before rebuilding?

**Comment by tacaswell** [comment]
Done, should be live when ever all of the caches clear (which is longer now that we have cloudflare involved).

If it is not gone by tonight re-ping (and I'll try to remember to check).

**Comment by tacaswell** [comment]
Sorry, I didn't see @matthew-brett 's last message before I did the rebuild and push.

**Comment by matthew-brett** [comment]
Lena's fully retired from my check just now.
