### ISSUE TITLE
Deployed site doesn't correspond to current repo contents

### ISSUE THREAD

**Issue by StefRe** [matplotlib/sampledoc#26]
https://matplotlib.org/sampledoc/index.html is outdated and contains some errrors that already have been fixed in the main branch 5 years ago (70f7888985).

**Comment by jklymak** [comment]
I had no idea this was even published anywhere.   I don't think it is maintained, and seems to have caused some confusion.  We should have a proper discussion about whether it should be kept around.

**Comment by timhoffm** [comment]
I suggest to remove this. Generic documentation how to set up sphinx is not our topic. There are enough resources that cover that.

And even if you don't want plain sphinx, but something more looking like the matplolib docs (maybe because you're a third party package building on top of matplotlib and want a similar look), nowadays the go-to is pydata-sphinx-theme.

**Comment by StefRe** [comment]
> I don't think it is maintained

certainly not, see also #25: the `only_directive` for instance was removed from matplotlib back in 2018 (https://github.com/matplotlib/matplotlib/pull/11295)

**Comment by StefRe** [comment]
> I had no idea this was even published anywhere

Neither did I. I just came across it by chance in https://github.com/ipython/ipython/pull/13751 when updating the [sphinx docs](https://ipython.readthedocs.io/en/stable/sphinxext.html?highlight=sphinxext#ipython-sphinx-directive-module) that refer to that published page (that's why I put a TODO reminder for myself in the PR).

**Comment by QuLogic** [comment]
The generated contents of this repo are a fixed part of https://github.com/matplotlib/matplotlib.github.com so I guess they only get updated whenever some feels like copying it there. We can set up proper pages hooks to publish and then drop the copy from there if we want, or just remove it.

I guess I'll just put it on the agenda for this week.

**Comment by jklymak** [comment]
@StefRe - We discussed on the call.  We would like to mothball this site.  Ideally ipython would take whatever they need from this and host in their docs.  We will move the useful parts for our purposes to our main docs.  But certainly ipython should not be linking to this (it has python 2 code in it, just a a zeroth order check!)

**Comment by StefRe** [comment]
> it has python 2 code in it, just a a zeroth order check!  

as I said: it's already fixed in the repo and there are some more minor fixes (#25), but the updated version is not published - that was my only point here

**Comment by jklymak** [comment]
The plan is not to publish the site generated here or continue to maintain it.
